docker-rest :
 image: nginx:alpine
 container_name: docker-rest
 hostname: docker-rest
 restart: always
 ports:
  - "11666:80"
 volumes:
  - "/opt/docker-rest/nginx.conf:/etc/nginx/nginx.conf:ro"
  - "/opt/docker-rest/.passwd:/etc/nginx/.passwd:ro"
  - "/opt/docker-rest/ssl:/etc/nginx/ssl:ro"
  - "/opt/docker-rest/www:/var/www:ro"
  - "/var/run/docker.sock:/var/run/docker.sock:rw"
